GET http://localhost:3637/infrabot/health

###
GET http://localhost:3637/infrabot/quote

###

POST http://localhost:3637/infrabot/noops
Content-Type: application/json

{
  "app": "node.js",
  "isNew": true,
  "repo": "https://github.com/reemuru/headerParse.git",
  "cwd": "headerParse",
  "install": {"cmd": "npm", "args": ["i"]},
  "tti": 30,
  "compile": null,
  "run": {"cmd": "node", "args": ["index.js"]},
  "payment_request": "lnbcrt100n1psvesvzpp5l0kz9exaj7nh6h3kzl5tn84v2d3wc6m8m75x5l8wxq3zqkls636sdq6d9hxvunpvfhhggrfdemx76trv5cqzpgsp5g8ctm0ehhjx4ulqy3q6sqc9q996g22urn82nqxd5r2ytr2mjch4s9qyyssqqn37afuch9lqffj9th2f6laj7r6eg2qj35y0l7qejk48jn4ecfvzytt2nxeh90gqsf5glvenexmgqn264j44u2jjwpeu4r7yeypkzdqpvu8ync",
  "ttl": "20"
}

### lsat testing
GET https://localhost:8081/infrabot/quote
# Authorization: LSAT AgEEbHNhdAJCAAAZJn7lsxygp6ejpS3S7Fq/ZiWKKFmx6ZTj1SFk4BWjACJRKhgST1+hGUvyVAgdgXFjXokAMP7di6t0MHboMwGVAAITc2VydmljZXM9aW5mcmFib3Q6MAACFmluZnJhYm90X2NhcGFiaWxpdGllcz0AAhZ2YWxpZF91bnRpbD0yMDIxLTEyLTEyAAIWdmFsaWRfdW50aWw9MjAyMi0xMi0xMgAABiAOzve9NVzNQYeBmbgydTY6CqG9ON7mb62qKfdByNBgrw==:3fb9664633ed6c9dfc217eee190f08aa1d5b722f9867f7ee27bda0a6c63abf20